---
AWSTemplateFormatVersion: 2010-09-09

Description: Elastic Container Repository

# Metadata:

# Parameters:

Resources:

# Container

  CreateBag:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: create-bag

Outputs:

  CreateBag:
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${CreateBag}
    Export:
      Name: !Sub ${AWS::StackName}-create-bag
